Added analysis to extraxt_tunneling in auxillary.py
Try to analyse group_list because of error when using it through BoseHubbardPropagation:

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (2, 3) + inhomogeneous part.